---
title: "Untitled"
author: "Juan José Merino Zarco"
date: "28/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Dataframes

```{r}
iris
```

```{r}
head(iris)
```
```{r}
tail(iris)
```

```{r}
dim(iris)
```

```{r}
summary(iris)
```

```{r}
str(iris)
```

##### Manipulacion de un dataframe

```{r}
head(iris)
q <- iris + 2
head(q)
```

## Subconjuntos de una estructura de datos

### Indice

```{r}
color <- c("rojo", "azul", "verde", "amarillo", "morado")
color
```

```{r}
color[4]
```

```{r}
color[5]
```

```{r}
color[1:3]
```
Nota: 

```{r}
color[-3]
```

```{r}
color[c(-1,-5)]
```
#### Dataframe

```{r}
head(iris)
```


```{r}
iris[1,2]
```


```{r}
iris[1,]
```

```{r}
iris[,1]
```


```{r}
iris[,c(1,3,5)]
```

```{r}
iris[c(1,3,5),]
```

```{r}
iris[c(1,3),c(1,3)]
```

```{r}
iris[1:50, c(1,3)]
```

```{r}
names(iris)
```

```{r}
iris["Sepal.Length"]
```

### Condicionales

> Data_frame[condicion, columnas_devueltas]




```{r}
q2 <- iris[iris$Petal.Length >= 5.5,]
summary(q2)
```


```{r}
q3 <- iris[iris$Petal.Length >= 1.5 & iris$Species== "setosa",]
summary(q3)
```

## Dplyr



## Funciones


```
nombre <- function(argumentos){
operaciones
}
```

### Area de un cuadrado

```{r}
area_cuadrado <- function(lado){
  lado*lado
}
```

```{r}
area_cuadrado(lado = 4)
```

```{r}
hist(iris$Sepal.Length)
```

```{r}
estadisticos_grafica <- function(Variable){
  hist(Variable)
  summary(Variable)
}
```




```{r}
estadisticos_grafica(Variable = iris$Sepal.Length)
```

```{r}
estadisticos_grafica(iris$Petal.Width)
```















> Como crear un dataframe en R 

```{r}
escolaridad <- c("primaria","secundaria")
ingresos <- c(100,200)
obj <- cbind(escolaridad,ingresos)
obj
obj2 <- rbind(obj, c("preparatoria", 300))
obj2
```


### Estructuras de control

### If y else

If: Si

else: de otro


```
if(condicion){operacion si la condicion es TRUE}else{Operacion si la condicion es falsa}
```

```{r}
if(5>3){"Verdadero"}else{"falso"}
```

```{r}
promedio <- function(calificaciones){
  prom <- mean(calificaciones)
  
  if(prom >= 6.6){"Pasa el año"}else{"Reprueba"}
}
```



```{r}
alumno1 <- promedio(c(7,8.8,8.5))
alumno1
```


























