---
title: "Taller R-Markdown"  
subtitle: "Sesion 5"
author:
- "Juan José Merino Zarco^[jmerinocm@gmail.com, Colegio de México]"
- "Adrian Hernandes Noli^[correo@gmail.com, Chapingo]"
date: '`r format(Sys.Date(), " %d de %B de %Y")`'
linkcolor: green
urlcolor: blue
fontsize: 11pt
mainfont: Arial
geometry: margin=1in
output:
  pdf_document:
    df_print: kable
    latex_engine: xelatex
    fig_caption: yes
    number_sections: yes
    toc_depth: 3
header-includes:
  - \usepackage[spanish]{babel}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

\newpage

\tableofcontents

\pagebreak

\listoffigures

\newpage


# YAML

```
---
title: "Taller R-Markdown"  
subtitle: "Sesion 5"
author:
- "Juan José Merino Zarco^[jmerinocm@gmail.com, Colegio de México]"
- "Adrian Hernandes Noli^[correo@gmail.com, Chapingo]"
date: '`r format(Sys.Date(), " %d de %B de %Y")`'
linkcolor: green
urlcolor: blue
fontsize: 11pt
mainfont: Arial
geometry: margin=1in
output:
  pdf_document:
    df_print: kable
    latex_engine: xelatex
    fig_caption: yes
    number_sections: yes
    toc_depth: 3
header-includes:
  - \usepackage[spanish]{babel}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
---
```

\newpage

```{r, child= 'T1 Taller.Rmd'}
```

\newpage

```{r, child= 'T2a.Rmd'}
```

\newpage

```{r, child= 'T2b.Rmd'}
```

